In [1]:
import tensorflow as tf

## use generator 

In [3]:
def gen():
    for i in range(10):
        yield i

In [4]:
dataset = tf.data.Dataset.from_generator(gen, tf.float32)\
        .make_one_shot_iterator()\
        .get_next()

In [8]:
with tf.Session() as sess:
    for _ in range(10):
        data_ = sess.run(dataset)
        print(data_)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [9]:
with tf.Session() as sess:
    for _ in range(11):
        data_ = sess.run(dataset)
        print(data_)  # end of sequence

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


OutOfRangeError: End of sequence
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[<unknown>], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "/home/fwani/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fwani/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-051b67089a1c>", line 2, in <module>
    dataset = tf.data.Dataset.from_generator(gen, tf.float32)        .make_one_shot_iterator()        .get_next()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 420, in get_next
    name=name)), self._output_types,
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[<unknown>], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]


In [17]:
def gen2():
#     for i, j in zip(range(10,20), range(10)):
    for i, j in zip(range(10,1010), range(1000)):
        yield (i,j)

In [27]:
dataset = tf.data.Dataset.from_generator(gen2, (tf.float32, tf.float32))\
        .shuffle(7777)\
        .batch(20)\
        .make_one_shot_iterator()\
        .get_next()
# shuffle(size)
# batch(size)

In [22]:
with tf.Session() as sess:
    for _ in range(3):
        feature_, label_ = sess.run(dataset)
        print(feature_, label_)

[ 497.  560.  700.  174.  407.  179.  883.  574.   91.  962.  261.  441.
  375.  880.  132.  298.  839.  769.   87.   54.] [ 487.  550.  690.  164.  397.  169.  873.  564.   81.  952.  251.  431.
  365.  870.  122.  288.  829.  759.   77.   44.]
[ 250.  323.  787.  297.  143.  940.  704.  243.  136.  964.  178.  232.
  936.  458.  501.  991.  104.  440.  413.  800.] [ 240.  313.  777.  287.  133.  930.  694.  233.  126.  954.  168.  222.
  926.  448.  491.  981.   94.  430.  403.  790.]
[ 902.  821.  878.  123.  226.  641.  449.  409.  256.  652.  851.  814.
  289.  570.  931.  871.  473.  322.  108.  259.] [ 892.  811.  868.  113.  216.  631.  439.  399.  246.  642.  841.  804.
  279.  560.  921.  861.  463.  312.   98.  249.]


## read text data

### no batch

In [28]:
dataset = tf.data.TextLineDataset('./up_down_dataset.csv')\
        .make_one_shot_iterator()\
        .get_next()

In [29]:
with tf.Session() as sess:
    data_ = sess.run(dataset)
    print(data_)

b'0,1,2,3,4,5,6,7,8,9,1'


In [36]:
lines = tf.decode_csv(dataset, record_defaults=[[0]]*11)
with tf.Session() as sess:
    print(sess.run(lines))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1]


In [39]:
feature = tf.stack(lines[:-1])#, axis=1)  # if no batch, then don't use axis=1
label = lines[-1]

In [40]:
with tf.Session() as sess:
    feat_, lab_ = sess.run([feature, label])
    print(feat_,lab_)

[0 1 2 3 4 5 6 7 8 9] 1


### with batch

In [ ]:
# dataset = tf.data.TFRecordDataset()  # for all of data type 

In [56]:
dataset = tf.data.TextLineDataset('./up_down_dataset.csv')\
        .batch(20)\
        .make_one_shot_iterator()\
        .get_next()
# for csv type

In [57]:
lines = tf.decode_csv(dataset, record_defaults=[[0]]*11)
with tf.Session() as sess:
    print(sess.run(lines))

[array([0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9], dtype=int32), array([1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8], dtype=int32), array([2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7], dtype=int32), array([3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6], dtype=int32), array([4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5], dtype=int32), array([5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4], dtype=int32), array([6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3], dtype=int32), array([7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2, 7, 2], dtype=int32), array([8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1, 8, 1], dtype=int32), array([9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0], dtype=int32), array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)]


In [58]:
feature = tf.stack(lines[:-1], axis=1)  # if no batch, then don't use axis=1
label = lines[-1]

In [59]:
with tf.Session() as sess:
    feat_, lab_ = sess.run([feature, label])
    print(feat_,lab_)

[[0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]] [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]


In [60]:
with tf.Session() as sess:
    feat_, lab_ = sess.run([feature, label])
    for f, l in zip(feat_,lab_):
        print(f,l)

[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0
[0 1 2 3 4 5 6 7 8 9] 1
[9 8 7 6 5 4 3 2 1 0] 0


In [61]:
with tf.Session() as sess:
    for i in range(100):
        feat_, lab_ = sess.run([feature, label])
        print(feat_.shape,lab_.shape)

(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(20, 10) (20,)
(10, 10) (10,)


OutOfRangeError: End of sequence
	 [[{{node IteratorGetNext_9}} = IteratorGetNext[output_shapes=[[?]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_9)]]

Caused by op 'IteratorGetNext_9', defined at:
  File "/home/fwani/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fwani/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-f66382d86393>", line 1, in <module>
    dataset = tf.data.TextLineDataset('./up_down_dataset.csv')        .batch(20)        .make_one_shot_iterator()        .get_next()
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 420, in get_next
    name=name)), self._output_types,
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/fwani/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[{{node IteratorGetNext_9}} = IteratorGetNext[output_shapes=[[?]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_9)]]
