In [1]:
import tensorflow as tf

In [2]:
# make tensor which is constant
const = tf.constant('hi tensorflow')
print(const)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
with tf.Session() as sess:
    const_ = sess.run(const)
    print(const_)

b'hi tensorflow'


In [4]:
mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat2 = [[2,2,2],[2,2,2],[2,2,2]]

In [5]:
t_mat1 = tf.constant(mat1)
t_mat2 = tf.constant(mat2)

print(t_mat1)
print(t_mat2)

Tensor("Const_1:0", shape=(3, 3), dtype=int32)
Tensor("Const_2:0", shape=(3, 3), dtype=int32)


In [6]:
result1 = tf.matmul(t_mat1, t_mat2)

In [7]:
result2 = tf.matmul(result1, t_mat2)

In [8]:
with tf.Session() as sess:
    r1_, r2_ = sess.run([result1, result2])
    print(r1_)
    print(r2_)

[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 72  72  72]
 [180 180 180]
 [288 288 288]]
